services:
  jenkins:
    image: jenkins-docker:latest
    container_name: jenkins
    ports:
      - 8081:8080
      - 5000:5000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  jenkins_home: